workspace = { members = ["spk-installer"] }
[package]
name = "spotikill"
version = "0.1.4"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
debug = false
lto = true
opt-level = "s"

[dependencies]
anyhow = "1.0"
const_format = "0.2"
notify-rust = "4"
sysinfo = "0.30"
tray-item = "0.9"

[build-dependencies]
windres = "0.2.2"
