[package]
name = "spotikill"
version = "0.1.2"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
const_format = "0.2"
notify-rust = "4"
sysinfo = "0.30"
tray-item = "0.9"
windows = { version = "0.52.0", features = ["Win32_UI_Shell"] }

[build-dependencies]
windres = "0.2.2"
