[package]
name = "spotikill"
version = "0.1.4"
edition = "2021"
default-run = "spotikill"

[[bin]]
name = "spotikill"
path = "src/main.rs"

[[bin]]
name = "installer"
path = "src/bin/installer/main.rs"
required-features = ["installer"]

[features]
installer = ["directories", "windows"]

[profile.release]
debug = false
lto = true
opt-level = "s"

[dependencies]
anyhow = "1.0"
const_format = "0.2"
directories = { version = "5.0", optional = true }
notify-rust = "4"
sysinfo = "0.30"
tray-item = "0.9"

[target.'cfg(windows)'.dependencies]
windows = { version = "0.52.0", optional = true }

[target.'cfg(windows)'.build-dependencies]
windres = "0.2.2"
