[package]
name = "spotikill"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.71"
const_format = { version = "0.2.31", features = ["rust_1_64"] }
notify-rust = "4.8.0"
sysinfo = "0.29.2"
tray-item = "0.8.0"

[build-dependencies]
windres = "0.2.2"
